package miniproject;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.eclipse.persistence.tools.profiler.Profile;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kbkotian
 */
public class login extends javax.swing.JFrame {
    
    String sql=null;
    String query=null;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Main
     */
    public login() {
        initComponents();
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        USERNAME_LOGIN = new javax.swing.JTextField();
        USERNAME_LABEL = new javax.swing.JLabel();
        PASSWORD_LABEL = new javax.swing.JLabel();
        LOGIN_BUTTON = new javax.swing.JButton();
        SIGNUP_BUTTON = new javax.swing.JButton();
        PASSWORD_LOGIN = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        USERNAME_LOGIN.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        USERNAME_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAME_LOGINActionPerformed(evt);
            }
        });

        USERNAME_LABEL.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        USERNAME_LABEL.setText("USERNAME");

        PASSWORD_LABEL.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        PASSWORD_LABEL.setText("PASSWORD");

        LOGIN_BUTTON.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        LOGIN_BUTTON.setText("LOGIN");
        LOGIN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BUTTONActionPerformed(evt);
            }
        });

        SIGNUP_BUTTON.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        SIGNUP_BUTTON.setText("SIGN UP");
        SIGNUP_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGNUP_BUTTONActionPerformed(evt);
            }
        });

        PASSWORD_LOGIN.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        PASSWORD_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORD_LOGINActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setText("EVENT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(USERNAME_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PASSWORD_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(USERNAME_LOGIN)
                            .addComponent(PASSWORD_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LOGIN_BUTTON)
                                .addGap(75, 75, 75)
                                .addComponent(SIGNUP_BUTTON))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USERNAME_LABEL))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD_LABEL)
                    .addComponent(PASSWORD_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOGIN_BUTTON)
                    .addComponent(SIGNUP_BUTTON))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void USERNAME_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAME_LOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAME_LOGINActionPerformed

    private void LOGIN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BUTTONActionPerformed
                     
         
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","MiniProject","MiniProject");
            
        }
        
        catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            sql="select C_USERNAME,C_PASSWORD from CUSTOMER where C_USERNAME=? and C_PASSWORD=?";
            pst=con.prepareStatement(sql);
            
            
            pst.setString(1, USERNAME_LOGIN.getText());
            pst.setString(2, PASSWORD_LOGIN.getText());
            rs=pst.executeQuery();    
            
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Login successfully by "+(USERNAME_LOGIN.getText()));
                dispose();
                
                
                event e = new event();
                event.USERNAME.setText(login.USERNAME_LOGIN.getText());
                e.setVisible(true);
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Username or Password Incorrect");
            }
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }                                        

                                         
public void close(){
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }//GEN-LAST:event_LOGIN_BUTTONActionPerformed

    private void PASSWORD_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORD_LOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORD_LOGINActionPerformed

    private void SIGNUP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGNUP_BUTTONActionPerformed
        // TODO add your handling code here:
          signup s = new signup();
          s.setVisible(true);
    }//GEN-LAST:event_SIGNUP_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGIN_BUTTON;
    private javax.swing.JLabel PASSWORD_LABEL;
    private javax.swing.JPasswordField PASSWORD_LOGIN;
    private javax.swing.JButton SIGNUP_BUTTON;
    private javax.swing.JLabel USERNAME_LABEL;
    public static javax.swing.JTextField USERNAME_LOGIN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
